add extra steps

diff --git a/.github/workflows/tf-aws.yml b/.github/workflows/tf-aws.yml
--- a/.github/workflows/tf-aws.yml
+++ b/.github/workflows/tf-aws.yml
@@ -85,12 +85,29 @@ jobs:
 
 
       # Test SSH connection
+      - name: Check SSH Key
+        run: |
+          if [ ! -f ./aws.pem ]; then
+            echo "ERROR: SSH key not found!"
+            exit 1
+          fi
+          ls -l ./aws.pem
+
+      - name: Set correct permissions for SSH key
+        run: chmod 400 ./aws.pem
+
+      - name: Check SSH Key Format
+        run: ssh-keygen -l -f ./aws.pem || echo "Invalid SSH key!"
+
+      - name: Convert SSH key to RSA format
+        run: ssh-keygen -p -m PEM -f ./aws.pem -o -P "" -N ""
+
       - name: Test SSH connection
         run: |
           INSTANCE_IP=$(terraform output -json k3s_vm_public_ip | jq -r 'if type == "string" then . else .[0] end')
 
           echo "Trying to SSH into $INSTANCE_IP"
-          ssh -v -o StrictHostKeyChecking=no -i ./aws.pem ubuntu@$INSTANCE_IP
+          ssh -vvv -o StrictHostKeyChecking=no -i ./aws.pem ubuntu@$INSTANCE_IP
 
 
       # Install Ansiblegit 
